(typeof window !== 'undefined' ? window : global).URLMap = {
  "/undefined": "https://ant.design/",
  "/": "https://ant.design/",
  "/date-picker-value": "https://ant.design/components/date-picker/#components-date-picker-demo-format",
  "/time-picker-value": "https://ant.design/components/time-picker/#components-time-picker-demo-size",
  "/calendar-value": "https://ant.design/components/calendar/#components-calendar-demo-custom-render",
  "/item-render": "https://ant.design/components/breadcrumb/#API",
  "/menu-on-open-change": "https://ant.design/components/menu/#components-menu-demo-sider-current",
  "/fixed-columns": "https://ant.design/components/table/#components-table-demo-fixed-columns",
  "/table-row-key": "https://ant.design/components/table/#Note",
  "/date-picker-on-open-change": "https://ant.design/components/date-picker/#components-date-picker-demo-start-end",
  "/popover-content": "https://ant.design/components/popover/#components-popover-demo-basic",
  "/get-field-decorator": "https://ant.design/components/form/#components-form-demo-horizontal-login",
  "/gg2moment": "https://github.com/ant-design/ant-design/commit/4026221d451b246956983bb42140142d4a48b7d7",
  "/codesandbox-repro": "https://codesandbox.io/api/v1/sandboxes/define?parameters=N4IgZglgNgpgziAXKADgQwMYGs0HMYB0AVnAPYB2SoGFALjObVSACYwoNvkYTzMBOMTE0QgoaenCYAaEIOEBaFqQC2SMRPgyQaRi3XjJ2laoYiQAJhABfW7Ijk2AD2IJkIGozPqIKlKX5aAAIAJSEMYLB-VSCAcnkI2IBuAB1yX39A0PDaABEAeQBZIKiY-JylVWS0jIDgkxUzEuiVOIazavS_OqDgINzNAAUIbBh-aSCANzG4CAog62ay3VoWTtqs2JWWAHoWCCkd7YIMODhOtLDhAsKCQUcxgAo0oKCAHn3JoKkAT1gAXmAfRUaH4uAciCCFgALAtrAA-F6vd4ob60P4wQHA0Hg8gAIVItFoqkhMLh8O2Uxmc3IkOA034swo1jeOxQiPIyPeA3ow1G_CCbDAaAArlBaAA1NBQEWY4DtRiPACUix28ORSNZn3h0iRygwIsajAI-FoAFFYEbaHifgBJFiPeKkQmxJVpJVJGz2B4uAAWtBUUGYnnojHUHwgXwgLH-KTkztocfhWsj8JstiAA",
};
