(typeof window !== 'undefined' ? window : global).URLMap = {
  "/undefined": "https://ant.design/",
  "/": "https://ant.design/",
  "/date-picker-value": "https://ant.design/components/date-picker/#components-date-picker-demo-format",
  "/time-picker-value": "https://ant.design/components/time-picker/#components-time-picker-demo-size",
  "/calendar-value": "https://ant.design/components/calendar/#components-calendar-demo-custom-render",
  "/item-render": "https://ant.design/components/breadcrumb/#API",
  "/menu-on-open-change": "https://ant.design/components/menu/#components-menu-demo-sider-current",
  "/fixed-columns": "https://ant.design/components/table/#components-table-demo-fixed-columns",
  "/table-row-key": "https://ant.design/components/table/#Note",
  "/date-picker-on-open-change": "https://ant.design/components/date-picker/#components-date-picker-demo-start-end",
  "/popover-content": "https://ant.design/components/popover/#components-popover-demo-basic",
  "/get-field-decorator": "https://ant.design/components/form/#components-form-demo-horizontal-login",
  "/locale": "https://ant.design/components/config-provider-cn/#components-config-provider-demo-locale",
  "/complex-form-item": "https://ant.design/components/form/#components-form-demo-complex-form-control",
  "/form-deps": "https://ant.design/components/form/#dependencies/",
  "/form-item-usestatus": "https://ant.design/components/form-cn#formitemusestatus",
  "/gg2moment": "https://github.com/ant-design/ant-design/commit/4026221d451b246956983bb42140142d4a48b7d7",
  "/codesandbox": "https://codesandbox.io/s/antd-reproduction-template-forked-jyh2k9",
  "/codesandbox-repro": "https://codesandbox.io/s/antd-reproduction-template-forked-jyh2k9",
  "/codesandbox-4x": "https://codesandbox.io/s/antd-reproduction-template-y9vgcf",
  "/codesandbox-repro-4x": "https://codesandbox.io/s/antd-reproduction-template-y9vgcf",
  "/pro-v2-default-settings": "https://github.com/ant-design/ant-design-pro/tree/master/src/defaultSettings.js",
  "/faq": "https://github.com/ant-design/ant-design/issues?q=is%3Aissue+label%3A%E2%9D%93FAQ+is%3Aclosed",
};
